# Numpy and Pandas Section Five Homework

<br>

### <ins>Let's learn some more!</ins> ###
1. What does Pandas stand for?
    <br> Pandas references "Panel Data" and "Python Data Analysis". 
2. What are the 2 collections used in Pandas?
<brk> Columns and DataFrames.
3. Name 4 things Pandas can do for us.
<brk> Panas can load, manipulate, prepare, and model data.
4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?
<brk> inplace=True
5. What is a CSV?
<brk> A CSV is text that stores tabular data with commas separating values.
6. When cleaning data what values do we not like in our data?
<brk> We do not like null values.


7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- .reshape()

8. Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

9. Make a Deep Copy of the above array

In [2]:
import numpy as np
import copy

arrayA = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
newarrayA = arrayA.reshape([2, 3, 2])
print(newarrayA)

arrayB = np.linspace(0, 20, num=6)
print(arrayB)

C = copy.deepcopy(arrayB)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 0.  4.  8. 12. 16. 20.]


Using Series, create a DataFrame that looks like this:

Ingredients	Quantity	Unit
Flour	4	cups
Milk	1	cup
Eggs	2	large
Spam	1	can
Name: Dinner, dtype: object

In [ ]:
#15

import numpy as np
import pandas as pd

ingredients = pd.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name ='Ingredients')
quantity = pd.Series([4, 1, 2, 1], name = 'Quantity')
unit = pd.Series(['cups', 'cup', 'large', 'can'], name = 'Unit')
Dinner = pd.concat([ingredients, quantity, unit], axis=1)
Dinner

In [ ]:
# 16. Create DataFrame named "Student Data"
import numpy as np
import pandas as pd

studentData = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'Sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
df = pd.DataFrame(studentData)
df


In [ ]:
# 17. Add a new column to the DataFrame with the following deserts: 
# ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
import pandas as pd
import numpy as np

dessert = ["Ice Cream", "Cashew Fudge", "Waffles", "Carrot Halwa"]
df.insert(6, "Dessert", dessert, True)
df

In [ ]:
#18. 
df.sort_values(by = ['Name', 'address'], ascending= [True, True])

In [ ]:
#19.
df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
df.to_csv("cows_and_goats.csv")

In [4]:
#20.
import copy
import pandas as pd
Garden = {
    "Veggies" : ["Cucumbers", "Zucchini", "Carrots"],
    "Yield" : [15, 23, 7],
    "Health" : ["Vibrant", "Plump", "Shriveled"]}

Rating = [10, 8, 2]
df = pd.DataFrame(Garden)
df.insert(2, "Rating", Rating, True)
df.to_csv("Copy1Veg.csv")
c = copy.deepcopy(df)
c.to_csv("VeggieGarden.csv")
c

,Veggies,Yield,Rating,Health
0,Cucumbers,15,10,Vibrant
1,Zucchini,23,8,Plump
2,Carrots,7,2,Shriveled
